/**
 * Timeline service — append-only domain operations for TimelineEvent.
 *
 * APPEND-ONLY CONTRACT:
 * - This service provides ONLY appendTimelineEntry() — no update, no delete.
 * - Corrections produce new events with amendsEventId pointing to the error.
 * - AI-sourced events can be appended but are marked source='ai_suggestion'
 *   and require human promotion before engine consumption.
 *
 * TWO-CLOCK PRINCIPLE:
 * - occurredAt: LEGAL TIME — when the event actually happened. Required.
 *   May be in the past (retroactive recording of historical facts).
 *   Cannot be more than 1 day in the future (clock skew tolerance only).
 * - recordedAt: SYSTEM TIME — set by DB default at INSERT. Never set by caller.
 *
 * SUPPORTED EVENT TYPES (Phase 4):
 * - internal notes (event_category='internal')
 * - intake events (event_category='document', 'internal')
 * - document associations (event_category='document')
 * - transfer events (event_category='prison')
 * - manual legal annotations (event_category='court', 'sentence', 'benefit', etc.)
 *
 * DEFERRED (Phase 5+):
 * - AI-sourced event promotion
 * - Engine-generated events
 * - Integration-sourced events
 *
 * Architecture ref: data-model-v1.md §2.5, event-state-architecture.md §3.
 */

import { withTx, unwrapOrThrow } from '../lib/tx.ts'
import { appendTimelineEvent as appendEventRepo } from '../repositories/timeline-event.ts'
import { findCaseById } from '../repositories/execution-case.ts'
import { writeAuditAndEvent } from './write-audit-event.ts'
import { ok, validationError, notFoundError, internalServiceError } from './result.ts'
import type { WriteContext } from '../lib/write-context.ts'
import type { ServiceResult } from './result.ts'
import type { TimelineEvent } from '@execflow/db/schema'
import type { TimelineEventCategory, TimelineEventSource, TimelineVisibility } from '@execflow/db/types'

// ---------------------------------------------------------------------------
// Input types
// ---------------------------------------------------------------------------

export type AppendTimelineEventInput = {
  /** UUID of the execution case this event belongs to. Required. */
  executionCaseId: string

  /**
   * Fine-grained event type identifier. Dot-namespaced free text.
   * Example: 'court.hearing', 'prison.transfer', 'office.note', 'document.registered'
   * Use 'office.note' for general operational notes.
   */
  eventType: string

  /**
   * Broad category for UI grouping and index filtering.
   * Must be a valid timeline_event_category value.
   */
  eventCategory: TimelineEventCategory

  /**
   * LEGAL TIME: when this event actually occurred in the real world.
   * May be in the past for retroactive recording. Required.
   * ISO 8601 datetime string.
   */
  occurredAt: string

  /**
   * Human-readable summary. Required.
   * Used in timeline display and legal narrative generation.
   */
  summary: string

  /**
   * Event-type–specific structured payload.
   * Validated by playbook system (Phase 5+). Stored as opaque JSON here.
   */
  payload?: Record<string, unknown> | undefined

  /**
   * How this event originated.
   * 'manual': human created it explicitly.
   * 'document': generated from a confirmed document.
   * 'system_rule': generated by a system rule.
   * AI-sourced ('ai_suggestion') and integration-sourced deferred to Phase 5+.
   */
  source?: TimelineEventSource | undefined

  /**
   * Event visibility.
   * 'internal': office-only, never in court-facing output.
   * 'legal': visible in legal narrative exports.
   * 'both': visible in both contexts.
   * Default: 'internal'.
   */
  visibility?: TimelineVisibility | undefined

  /**
   * When this event CORRECTS a prior erroneous event.
   * The prior event remains in history; this event supersedes it logically.
   * Both events are permanently stored (immutable history).
   */
  amendsEventId?: string | undefined

  /**
   * Polymorphic source reference (type + id).
   * Example: sourceRefType='Document', sourceRefId='uuid'
   */
  sourceRefType?: string | undefined
  sourceRefId?: string | undefined
}

// ---------------------------------------------------------------------------
// Service operations
// ---------------------------------------------------------------------------

/**
 * Append an immutable timeline event to a case's legal history.
 *
 * Validation:
 * - executionCaseId must refer to an existing case in this org
 * - occurredAt is required and must be a valid date
 * - occurredAt cannot be more than 1 day in the future (clock skew only)
 * - summary is required
 * - eventType is required (free text, not enum-validated here)
 *
 * Writes atomically: TimelineEvent + AuditLog + DomainEvent.
 *
 * REPLAY SAFETY: recordedAt is set by the DB, ensuring system ingestion time
 * is always accurate regardless of the occurredAt value.
 */
export async function appendTimelineEntry(
  ctx: WriteContext,
  input: AppendTimelineEventInput
): Promise<ServiceResult<TimelineEvent>> {
  // -------------------------------------------------------------------------
  // 1. Domain validation
  // -------------------------------------------------------------------------

  if (!input.executionCaseId) {
    return validationError('executionCaseId is required.', 'executionCaseId')
  }
  if (!input.eventType.trim()) {
    return validationError('eventType is required.', 'eventType')
  }
  if (!input.summary.trim()) {
    return validationError('summary is required.', 'summary')
  }
  if (!input.occurredAt) {
    return validationError('occurredAt (legal time) is required.', 'occurredAt')
  }

  const occurredAt = new Date(input.occurredAt)
  if (isNaN(occurredAt.getTime())) {
    return validationError('occurredAt must be a valid ISO 8601 datetime.', 'occurredAt')
  }

  // Reject future dates beyond 1 day (clock skew tolerance)
  const oneDayFromNow = new Date(Date.now() + 86_400_000)
  if (occurredAt > oneDayFromNow) {
    return validationError(
      'occurredAt cannot be more than 1 day in the future. Use the actual legal event date.',
      'occurredAt'
    )
  }

  // -------------------------------------------------------------------------
  // 2. Pre-condition checks (pre-transaction reads)
  // -------------------------------------------------------------------------

  const caseResult = await findCaseById(ctx.db, ctx.organizationId, input.executionCaseId)
  if (!caseResult.success) {
    return notFoundError('Execution case not found in this organization.')
  }

  const executionCase = caseResult.data

  // Archived cases accept read-only access; events can still be appended
  // for legal history completeness. Service does NOT restrict on case status.

  // -------------------------------------------------------------------------
  // 3. Transactional write
  // -------------------------------------------------------------------------

  try {
    const event = await withTx(ctx.db, async (tx) => {
      const eventResult = unwrapOrThrow(
        await appendEventRepo(tx, {
          organizationId: ctx.organizationId,
          executionCaseId: input.executionCaseId,
          eventType: input.eventType.trim(),
          eventCategory: input.eventCategory,
          occurredAt,
          // recordedAt: set by DB default (NOW()) — NOT set by caller
          summary: input.summary.trim(),
          payload: input.payload ?? {},
          source: input.source ?? 'manual',
          sourceRefType: input.sourceRefType,
          sourceRefId: input.sourceRefId,
          authorUserId: ctx.userId,
          actorType: ctx.actor.actorType,
          actorId: ctx.actor.actorId,
          visibility: input.visibility ?? 'internal',
          amendsEventId: input.amendsEventId,
        })
      )

      await writeAuditAndEvent({
        tx,
        actor: ctx.actor,
        organizationId: ctx.organizationId,
        requestId: ctx.requestId,
        correlationId: ctx.correlationId,
        action: 'created',
        entityType: 'TimelineEvent',
        entityId: eventResult.id,
        changes: {
          type: 'creation',
          snapshot: {
            eventType: input.eventType.trim(),
            eventCategory: input.eventCategory,
            occurredAt: occurredAt.toISOString(),
            source: input.source ?? 'manual',
            visibility: input.visibility ?? 'internal',
          },
        },
        eventType: 'timeline.event.appended',
        aggregateType: 'ExecutionCase',
        aggregateId: input.executionCaseId,
        occurredAt,
        eventPayload: {
          timelineEventId: eventResult.id,
          executionCaseId: input.executionCaseId,
          organizationId: ctx.organizationId,
          eventType: input.eventType.trim(),
          eventCategory: input.eventCategory,
          occurredAt: occurredAt.toISOString(),
          source: input.source ?? 'manual',
          visibility: input.visibility ?? 'internal',
          amendsEventId: input.amendsEventId ?? null,
          caseStatus: executionCase.status,
        },
      })

      return eventResult
    })

    return ok(event)
  } catch (err) {
    console.error('[timeline.service] appendTimelineEntry failed:', err)
    return internalServiceError('Failed to append timeline event.', err)
  }
}
