-- Seed das 102 fotos originais (geradas por raw/build.py e servidas estaticamente).
-- Idempotente: url é única, reexecutar não duplica.
insert into photos (url, category, caption, sort_order, is_cover, source) values
('/assets/img/080.jpg','mais','Cabana Afrodite',0,true,'builtin'),
('/assets/img/082.jpg','mais','Cabana Afrodite',1,false,'builtin'),
('/assets/img/086.jpg','mais','Cabana Afrodite',2,false,'builtin'),
('/assets/img/081.jpg','mais','Cabana Afrodite',3,false,'builtin'),
('/assets/img/001.jpg','interior','Sala de estar',4,false,'builtin'),
('/assets/img/000.jpg','interior','Sala de estar',5,false,'builtin'),
('/assets/img/003.jpg','interior','Sala de estar',6,false,'builtin'),
('/assets/img/031.jpg','externa','Área externa',7,false,'builtin'),
('/assets/img/032.jpg','externa','Área externa',8,false,'builtin'),
('/assets/img/033.jpg','externa','Área externa',9,false,'builtin'),
('/assets/img/034.jpg','externa','Área externa',10,false,'builtin'),
('/assets/img/035.jpg','externa','Área externa',11,false,'builtin'),
('/assets/img/036.jpg','externa','Área externa',12,false,'builtin'),
('/assets/img/037.jpg','externa','Área externa',13,false,'builtin'),
('/assets/img/020.jpg','quarto','Quarto',14,false,'builtin'),
('/assets/img/021.jpg','quarto','Quarto',15,false,'builtin'),
('/assets/img/022.jpg','quarto','Quarto',16,false,'builtin'),
('/assets/img/023.jpg','quarto','Quarto',17,false,'builtin'),
('/assets/img/024.jpg','quarto','Quarto',18,false,'builtin'),
('/assets/img/025.jpg','banho','Banheiro',19,false,'builtin'),
('/assets/img/026.jpg','banho','Banheiro',20,false,'builtin'),
('/assets/img/027.jpg','banho','Banheiro',21,false,'builtin'),
('/assets/img/028.jpg','banho','Banheiro',22,false,'builtin'),
('/assets/img/029.jpg','banho','Banheiro',23,false,'builtin'),
('/assets/img/030.jpg','banho','Banheiro',24,false,'builtin'),
('/assets/img/002.jpg','interior','Sala de estar',25,false,'builtin'),
('/assets/img/038.jpg','interior','Lareira',26,false,'builtin'),
('/assets/img/011.jpg','interior','Sala de jantar',27,false,'builtin'),
('/assets/img/012.jpg','interior','Sala de jantar',28,false,'builtin'),
('/assets/img/013.jpg','interior','Sala de jantar',29,false,'builtin'),
('/assets/img/014.jpg','interior','Sala de jantar',30,false,'builtin'),
('/assets/img/015.jpg','interior','Sala de jantar',31,false,'builtin'),
('/assets/img/016.jpg','interior','Sala de jantar',32,false,'builtin'),
('/assets/img/017.jpg','interior','Sala de jantar',33,false,'builtin'),
('/assets/img/018.jpg','interior','Sala de jantar',34,false,'builtin'),
('/assets/img/019.jpg','interior','Sala de jantar',35,false,'builtin'),
('/assets/img/004.jpg','interior','Cozinha',36,false,'builtin'),
('/assets/img/005.jpg','interior','Cozinha',37,false,'builtin'),
('/assets/img/006.jpg','interior','Cozinha',38,false,'builtin'),
('/assets/img/007.jpg','interior','Cozinha',39,false,'builtin'),
('/assets/img/008.jpg','interior','Cozinha',40,false,'builtin'),
('/assets/img/009.jpg','interior','Cozinha',41,false,'builtin'),
('/assets/img/010.jpg','interior','Cozinha',42,false,'builtin'),
('/assets/img/039.jpg','interior','Adega',43,false,'builtin'),
('/assets/img/040.jpg','interior','Adega',44,false,'builtin'),
('/assets/img/041.jpg','interior','Adega',45,false,'builtin'),
('/assets/img/042.jpg','interior','Adega',46,false,'builtin'),
('/assets/img/043.jpg','interior','Adega',47,false,'builtin'),
('/assets/img/044.jpg','mais','Cabana Afrodite',48,false,'builtin'),
('/assets/img/045.jpg','mais','Cabana Afrodite',49,false,'builtin'),
('/assets/img/046.jpg','mais','Cabana Afrodite',50,false,'builtin'),
('/assets/img/047.jpg','mais','Cabana Afrodite',51,false,'builtin'),
('/assets/img/048.jpg','mais','Cabana Afrodite',52,false,'builtin'),
('/assets/img/049.jpg','mais','Cabana Afrodite',53,false,'builtin'),
('/assets/img/050.jpg','mais','Cabana Afrodite',54,false,'builtin'),
('/assets/img/051.jpg','mais','Cabana Afrodite',55,false,'builtin'),
('/assets/img/052.jpg','mais','Cabana Afrodite',56,false,'builtin'),
('/assets/img/053.jpg','mais','Cabana Afrodite',57,false,'builtin'),
('/assets/img/054.jpg','mais','Cabana Afrodite',58,false,'builtin'),
('/assets/img/055.jpg','mais','Cabana Afrodite',59,false,'builtin'),
('/assets/img/056.jpg','mais','Cabana Afrodite',60,false,'builtin'),
('/assets/img/057.jpg','mais','Cabana Afrodite',61,false,'builtin'),
('/assets/img/058.jpg','mais','Cabana Afrodite',62,false,'builtin'),
('/assets/img/059.jpg','mais','Cabana Afrodite',63,false,'builtin'),
('/assets/img/060.jpg','mais','Cabana Afrodite',64,false,'builtin'),
('/assets/img/061.jpg','mais','Cabana Afrodite',65,false,'builtin'),
('/assets/img/062.jpg','mais','Cabana Afrodite',66,false,'builtin'),
('/assets/img/063.jpg','mais','Cabana Afrodite',67,false,'builtin'),
('/assets/img/064.jpg','mais','Cabana Afrodite',68,false,'builtin'),
('/assets/img/065.jpg','mais','Cabana Afrodite',69,false,'builtin'),
('/assets/img/066.jpg','mais','Cabana Afrodite',70,false,'builtin'),
('/assets/img/067.jpg','mais','Cabana Afrodite',71,false,'builtin'),
('/assets/img/068.jpg','mais','Cabana Afrodite',72,false,'builtin'),
('/assets/img/069.jpg','mais','Cabana Afrodite',73,false,'builtin'),
('/assets/img/070.jpg','mais','Cabana Afrodite',74,false,'builtin'),
('/assets/img/071.jpg','mais','Cabana Afrodite',75,false,'builtin'),
('/assets/img/072.jpg','mais','Cabana Afrodite',76,false,'builtin'),
('/assets/img/073.jpg','mais','Cabana Afrodite',77,false,'builtin'),
('/assets/img/074.jpg','mais','Cabana Afrodite',78,false,'builtin'),
('/assets/img/075.jpg','mais','Cabana Afrodite',79,false,'builtin'),
('/assets/img/076.jpg','mais','Cabana Afrodite',80,false,'builtin'),
('/assets/img/077.jpg','mais','Cabana Afrodite',81,false,'builtin'),
('/assets/img/078.jpg','mais','Cabana Afrodite',82,false,'builtin'),
('/assets/img/079.jpg','mais','Cabana Afrodite',83,false,'builtin'),
('/assets/img/083.jpg','mais','Cabana Afrodite',84,false,'builtin'),
('/assets/img/084.jpg','mais','Cabana Afrodite',85,false,'builtin'),
('/assets/img/085.jpg','mais','Cabana Afrodite',86,false,'builtin'),
('/assets/img/087.jpg','mais','Cabana Afrodite',87,false,'builtin'),
('/assets/img/088.jpg','mais','Cabana Afrodite',88,false,'builtin'),
('/assets/img/089.jpg','mais','Cabana Afrodite',89,false,'builtin'),
('/assets/img/090.jpg','mais','Cabana Afrodite',90,false,'builtin'),
('/assets/img/091.jpg','mais','Cabana Afrodite',91,false,'builtin'),
('/assets/img/092.jpg','mais','Cabana Afrodite',92,false,'builtin'),
('/assets/img/093.jpg','mais','Cabana Afrodite',93,false,'builtin'),
('/assets/img/094.jpg','mais','Cabana Afrodite',94,false,'builtin'),
('/assets/img/095.jpg','mais','Cabana Afrodite',95,false,'builtin'),
('/assets/img/096.jpg','mais','Cabana Afrodite',96,false,'builtin'),
('/assets/img/097.jpg','mais','Cabana Afrodite',97,false,'builtin'),
('/assets/img/098.jpg','mais','Cabana Afrodite',98,false,'builtin'),
('/assets/img/099.jpg','mais','Cabana Afrodite',99,false,'builtin'),
('/assets/img/100.jpg','mais','Cabana Afrodite',100,false,'builtin'),
('/assets/img/101.jpg','mais','Cabana Afrodite',101,false,'builtin')
on conflict (url) do nothing;
