/**
 * QueueEscalation — append-only record of every escalation event.
 *
 * APPEND-ONLY CONTRACT: immutable after creation. No updates, no deletes.
 *
 * A QueueEscalation row is written whenever:
 * - An SLA breach is detected for a queue item or workflow task
 * - An escalation level transition occurs (level 0 → 1 → 2 → 3)
 * - A liberty-risk item is flagged
 * - A human manually escalates a queue item
 *
 * WHY APPEND-ONLY:
 * Escalation history is a legal accountability record in a firm context.
 * "Who was notified, when, about what, and why the SLA was missed" must be
 * permanently retained for malpractice defense and operational review.
 *
 * Architecture ref: execution-workflows.md §4.5, office-operating-system.md §6,
 *                   office-operating-system.md §7.4.
 */

import {
  pgTable, uuid, text, timestamp, integer, jsonb, index,
} from 'drizzle-orm/pg-core'
import { organizations } from './organization.ts'
import { escalationTriggerEnum } from './_enums-queue.ts'

export const queueEscalations = pgTable(
  'queue_escalations',
  {
    // -------------------------------------------------------------------------
    // Identity — immutable
    // -------------------------------------------------------------------------

    id: uuid('id').primaryKey().defaultRandom(),

    // -------------------------------------------------------------------------
    // Tenant isolation
    // -------------------------------------------------------------------------

    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),

    // -------------------------------------------------------------------------
    // Target entity
    // -------------------------------------------------------------------------

    /**
     * 'QueueProjection', 'WorkflowTask', 'Deadline', or 'Opportunity'
     */
    targetEntityType: text('target_entity_type').notNull(),

    /** UUID of the affected entity. */
    targetEntityId: uuid('target_entity_id').notNull(),

    // -------------------------------------------------------------------------
    // Escalation record
    // -------------------------------------------------------------------------

    /** What triggered this escalation. */
    trigger: escalationTriggerEnum('trigger').notNull(),

    /** The escalation level BEFORE this event. */
    previousLevel: integer('previous_level').notNull(),

    /** The escalation level AFTER this event. */
    newLevel: integer('new_level').notNull(),

    // -------------------------------------------------------------------------
    // Notification targets
    // -------------------------------------------------------------------------

    /**
     * Users notified as part of this escalation.
     * Schema: [{ userId: string, role: 'assignee'|'lawyer'|'admin', channel: 'in_app'|'email'|'sms' }]
     */
    notifiedUsers: jsonb('notified_users'),

    // -------------------------------------------------------------------------
    // Context
    // -------------------------------------------------------------------------

    /**
     * Human-readable description of why this escalation occurred.
     * Generated by the SLA engine or provided by the escalating user.
     */
    escalationReason: text('escalation_reason'),

    /**
     * Key date that was breached (e.g., SLA deadline, legal due_at).
     * Captured at escalation time for immutable reference.
     */
    breachedAt: timestamp('breached_at', { withTimezone: true }),

    /**
     * How many days/hours the SLA was exceeded at escalation time.
     * Captured for operational metrics.
     */
    slaBreach: jsonb('sla_breach'),

    // -------------------------------------------------------------------------
    // Attribution
    // -------------------------------------------------------------------------

    /**
     * Actor type who triggered the escalation.
     * 'system': SLA monitor sweep
     * 'user': human manually escalated
     */
    actorType: text('actor_type').notNull().default('system'),

    /** UUID of the user if actor_type = 'user'. */
    actorId: text('actor_id').notNull(),

    /**
     * System time of the escalation.
     * Set by DB default — never set by application code.
     */
    escalatedAt: timestamp('escalated_at', { withTimezone: true }).notNull().defaultNow(),

    // -------------------------------------------------------------------------
    // Causality
    // -------------------------------------------------------------------------

    /** Domain event that triggered this escalation (null for cron-triggered). */
    causingEventId: uuid('causing_event_id'),

    /** Correlation ID for tracing through the escalation chain. */
    correlationId: uuid('correlation_id').notNull(),
  },
  (table) => [
    /**
     * Escalation history for a specific entity.
     */
    index('queue_escalations_entity_idx').on(
      table.targetEntityType,
      table.targetEntityId,
      table.escalatedAt
    ),

    /**
     * Org-level escalation feed: "all escalations in org X today"
     */
    index('queue_escalations_org_idx').on(
      table.organizationId,
      table.escalatedAt
    ),

    /**
     * Liberty risk query: "all liberty-risk escalations"
     * The SLA monitor uses this for breach analytics.
     */
    index('queue_escalations_trigger_idx').on(
      table.organizationId,
      table.trigger,
      table.escalatedAt
    ),
  ]
)

export type QueueEscalation = typeof queueEscalations.$inferSelect
export type NewQueueEscalation = typeof queueEscalations.$inferInsert
